# Busca o GO
FROM golang:1.22-alpine 

# Pasta de trabalho 
WORKDIR /app

# Copia a main client para o docker
COPY main.go sensores.go

# Da um build na main client
RUN go build -o sensores sensores.go

# Roda o executável
CMD [ "./sensores" ]