# Busca o GO
FROM golang:1.22-alpine 

# Pasta de trabalho 
WORKDIR /app

# Copia a main client para o docker
COPY atuador.go atuador.go

# Da um build na main client
RUN go build -o atuadores atuador.go

# Roda o executável
CMD [ "./atuadores" ]